### ISSUE TITLE
文档扩充

### ISSUE THREAD

**Issue by woshishabii** [aioqzone/aioqzone-feed#163]
请问能否扩充一下文档（添加如获取说说列表的代码示例），不太懂async代码看不太懂
谢谢

**Comment by JamzumSum** [comment]
> 请问能否扩充一下文档（添加如获取说说列表的代码示例），不太懂async代码看不太懂 谢谢

https://aioqzone.github.io/aioqzone-feed/examples.html

**Comment by woshishabii** [comment]
欧 好的谢谢
